### ISSUE TITLE
This is not a valid plugin error

### ISSUE THREAD

**Issue by ghost** [BGSU-LITS/LDAP-Plugin#2]
I've downloaded Version 0.3.0 from github and moved the files to the plugins folder of our dev instance of Omeka version 2.2.

When I go to the plugins page of the site, I cannot install.  Error is:
This is not a valid plugin

Permissions look the same as other plugins 755 for the plugin directories, 644 for plugin files.

**Comment by clas-web** [comment]
I've figured out why this was not working.  The name of the plugin folder that was in the zip file I downloaded from this is was "Ldap-0.3.0"  When I changed this folder name to "Ldap" it worked properly
