### ISSUE TITLE
Update form for 2.2.2

### ISSUE THREAD

**Issue by patrickmj** [BGSU-LITS/LDAP-Plugin#3]
Reported on Omeka forums http://omeka.org/forums/topic/ldap-plugin-needs-updates-for-version-222#post-103372

The `setSubmitButtonText()` function on the User Form in the UserController was removed in 2.2, so I expect that's the quick fix.

**Comment by misilot** [comment]
Was wondering if there was any update on this? As I would like to upgrade to 2.2.2

**Comment by daveWid** [comment]
I have actually moved on from my position at the BGSU Library and don't use Omeka any longer. If someone wants to submit a pull request with a fix I'll gladly merge it in but I'm not actively working on this codebase anymore.

If you know anyone who wants to take this over I'd be glad to redirect this repo over.

**Comment by misilot** [comment]
@patrickmj I would check out PR #1

**Comment by kloor** [comment]
The pull request was merged. I've also released a new plugin that provides both CAS and LDAP authentication for Omeka 2.2.2:
https://github.com/BGSU-LITS/omeka-plugin-CentralAuth
